### ISSUE TITLE
Block interaction Issues with crawling and swimming.

### ISSUE THREAD

**Issue by MomentiumENGINE** [doch2/SmartMovingReboot#12]
When crawling and swimming, the player can not enter one block spaces. Two blocks is still required as if traversing normally.
Also, if the player is crawling, they are unable to stand up unless the blocks above the player are at minimum 3 blocks in height.
Even when the default player can stand in two block spaces, they can not get up from the crawling position.

**Comment by doch2** [comment]
This issue is already recognized, and will be solved in redevelopment using the Obsuscate library.
