### ISSUE TITLE
Modpack crash | Conflict with MorePlayerModels Mode

### ISSUE THREAD

**Issue by Taknax** [doch2/SmartMovingReboot#2]
Here is my first try. Its crashin.
I send you log and chrashlog.

Crashlog
https://pastebin.com/juiFaXnC

Latestlog
https://pastebin.com/AhPvPgkg

I have MorePlayerModels intalled, which is changing the render abit. I hope we can find the issue.

Edit: I tried without MPM and the issue was gone. Thats really sad because MPM is really needet in my pack. Their is a issue with rendering. For years i tried to fix it. This time their was some issues with rendering by pressing F5 to switch to third person view. I hope you can fix this issue.

**Comment by doch2** [comment]
I will send you a comment again after checking the bug. Perhaps, Can you give me the link to the your's mode pack?

**Comment by Taknax** [comment]
Ok. The pack is not uploadet. Do you need a list of my mods?

**Comment by doch2** [comment]
I need your mod list to reproduce the bug. Can you leave a comment here?

**Comment by Taknax** [comment]
Ofc. Here:
https://pastebin.com/94CdewRj

**Comment by Taknax** [comment]
MorePlayerModels is not in the list.
https://www.curseforge.com/minecraft/mc-mods/more-player-models

**Comment by doch2** [comment]
Um.. There are so many mods, can you compress the mods file and send it to me? If you can send us the compressed file, please send it to 'dohui.ryu@kakao.com'.

**Comment by Taknax** [comment]
I send you my whole modpack, when i am at home tonight.

**Comment by Taknax** [comment]
Here is my modpack. The important files all their.
https://drive.google.com/drive/folders/1bFBqYAPQmmVDmaHHyK3E_K4tbfmeeIKM?usp=sharing

**Comment by doch2** [comment]
The file cannot be downloaded because it doesn't have permission. Can I change the file permissions to "open to anyone with the link'' in Google Drive?

**Comment by Taknax** [comment]
I am sry. This time it should work. If not i make a dropbox link.

https://drive.google.com/folderview?id=1smQgx17hZjv9YBEkehXMmkaQVBRQpgfi

**Comment by Taknax** [comment]
Its not even needet. To reproduce the bug install SM with the APIs and install MorePlayerModels. Start the game and click F5 to change in third person view. The bug show up.

**Comment by doch2** [comment]
The conflict with the MorePlayerModels mod seems to be difficult to resolve in the current version. Since both SmartMoving and MorePlayerModels mods use Minecraft's ModelBiped class modified, it is difficult for both mods to work without conflicting unless one of the mods is newly developed from scratch. Therefore, it is recommended to select one of the two mods and put them in the mod pack.

And the phenomenon that the game crashes when pressing F5 after starting the game did not appear when I ran it using the rest of your mode except for MorePlayerModels mode. Please check if you misunderstood that you did not use MorePlayerModels mode and make a comment again after testing.

**Comment by Taknax** [comment]
I figured out the same. Are you gonna investing in resolving this, to make MPM and SM compatible?

**Comment by doch2** [comment]
In the present version, modifying the code for compatibility with MPM is too hard for performance. Trying to use both modes as it is will be difficult unless the MPM creator modifies his mode and makes it compatible.

However, this problem will be solved automatically when redeveloping using the obfuscate library.

**Comment by Taknax** [comment]
Nice solution. And the rest works like charm! The best way is to go with Obfuscate. I close the issue. Ty for you time and you work!
