### ISSUE TITLE
elytra flying bug

### ISSUE THREAD

**Issue by Dancbeunny98** [doch2/SmartMovingReboot#4]
![image](https://user-images.githubusercontent.com/37336183/111921845-def98c80-8aa7-11eb-9371-ab47cdafc8eb.png)

**Comment by Dancbeunny98** [comment]
![image](https://user-images.githubusercontent.com/37336183/111921862-f2a4f300-8aa7-11eb-98c1-9fe44613e281.png)

**Comment by doch2** [comment]
I already know about this error. This is a problem that occurs because the existing source code does not compatible the 1.12.2 version. The existing source code is too complex, and you need to redevelop the mode with Obfuscate to fix this problem.

**Comment by LimerenceCantCode** [comment]
Any specifics to look at? I know vanilla movement is intercepted, perhaps the solution is as easy as adding an if statement that allows vanilla to reassert itself if the person is in the air with an elytra?

**Comment by doch2** [comment]
@LimerenceCantCode 

Oh, I've never thought of your solution, but I think it's good.

It would be great if you could solve this bug and then make a Pull Request to contribute!
