### ISSUE TITLE
[문제] 스마트무빙을 사용하면 커스텀npc에서 npc의 모양이 이상합니다.

### ISSUE THREAD

**Issue by MRuNanM** [doch2/SmartMovingReboot#9]
커스텀npc모드에서 npc의 모양이 한곳으로 겹친 형태로 됩니다. 64x32는 정상적으로 되나 기본 NPC가 없으면 워크샵등 많은 곳에 사용이 되지 않습니다.

**Comment by doch2** [comment]
일단은 스마트무빙 모드를 적용했을 시 커스텀npc는 64x32 사이즈의 모델만 정상적으로 작동합니다.

동시 적용하실 경우 그 모델로 사용하셔야 하며, Obfuscate 라이브러리를 이용한 재개발을 할 시에 해결될 문제라고 생각됩니다.

**Comment by MRuNanM** [comment]
그럼 언젠가는 해결이 가능한 건가요?

**Comment by doch2** [comment]
네네 곧 재개발 할 것 이기 때문에 곧 수정될 예정입니다.

**Comment by MRuNanM** [comment]
해결되지 못한다는 의미인가요?

**Comment by doch2** [comment]
아직 버그가 수정되지 않았다는 뜻입니다.
